version: '3.7'
services:
  mtct:
    image: mtct:latest
    container_name: mtct
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev
volumes:
  node_modules:
